package cloud_netstore.client;

import cloud_netstore.client.ClientHandler;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class ClientMainForm extends JFrame {
    private JPanel MainPane;
    private JButton butStart;
    private JButton butStop;
    private JButton butSendFile;
    private JTextField textLogin;
    private JTextField textPass;
    private JTextField textField1;
    private JTextArea textAreaMessages;
    private JButton butReceive;

    private ClientHandler clientHandler;

    public ClientMainForm() {

        clientHandler = new ClientHandler();

        butStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String str = clientHandler.connection();
                setTextAreaMessages(str);
            }
        });
        butSendFile.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.showOpenDialog(getMainPane());
                File file = fileChooser.getSelectedFile();
                String path = file.getName();
                setTextAreaMessages("File selected: " + path);
                // отправляем файл
                try {
                    clientHandler.sendFile(file, path);
                    setTextAreaMessages("File is sent");
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        });

        butStop.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    clientHandler.disconnect();
                    setTextAreaMessages("Disconnected");
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        });
        butReceive.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                clientHandler.receiveFile();
            }
        });
    }

    public JPanel getMainPane() {
        return MainPane;
    }

    public void setTextAreaMessages(String textAreaMessages) {
        this.textAreaMessages.append(new SimpleDateFormat("yyyy-MM-dd hh:mm:ss").format(new Date()) + " " + textAreaMessages + "\n");
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPane = new JPanel();
        MainPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        MainPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Authorization"));
        final JLabel label1 = new JLabel();
        label1.setText("Login:");
        panel2.add(label1);
        textLogin = new JTextField();
        textLogin.setMargin(new Insets(2, 5, 2, 5));
        textLogin.setMinimumSize(new Dimension(64, 24));
        textLogin.setPreferredSize(new Dimension(50, 28));
        textLogin.setText("");
        panel2.add(textLogin);
        final JLabel label2 = new JLabel();
        label2.setText("Password:");
        panel2.add(label2);
        textField1 = new JTextField();
        textField1.setPreferredSize(new Dimension(64, 28));
        panel2.add(textField1);
        final JLabel label3 = new JLabel();
        label3.setText("Server adress:");
        panel2.add(label3);
        textPass = new JTextField();
        textPass.setPreferredSize(new Dimension(64, 28));
        panel2.add(textPass);
        butStart = new JButton();
        butStart.setText("Connect");
        panel2.add(butStart);
        butStop = new JButton();
        butStop.setText("Disconnect");
        panel2.add(butStop);
        butSendFile = new JButton();
        butSendFile.setText("Send");
        panel1.add(butSendFile, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        textAreaMessages = new JTextArea();
        panel1.add(textAreaMessages, new GridConstraints(1, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        butReceive = new JButton();
        butReceive.setText("Receive");
        panel1.add(butReceive, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label1.setLabelFor(textLogin);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPane;
    }

}
